name: Veracode Static Pipeline Scanner

on:
  workflow_call:
    inputs:
      veracodeArtifact:
        required: false
        type: string
      policyName:
        required: false
        type: string
      failOnSeverity:
        required: false
        type: string
      failOnCWE:
        required: false
        type: string
      baselineFile:
        required: false
        type: string
      failBuild:
        required: true
        type: string
      moduleScannable:
        required: false
        type: string

jobs:
  pipeline_scan:
    runs-on: ubuntu-latest
    name: pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory
      
      # run the pipeline scan action
      - name: Veracode Pipeline-Scan
        id: pipeline-scan
        env:
          VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: ${{ inputs.veracodeArtifact }}
          fail_build: ${{ inputs.failBuild }}
          issue_details: true
          veracode_policy_name: ${{ inputs.policyName }}
          policy_file: ${{ inputs.policyName }}.json

      # save json results
      - name: save json results
        uses: actions/upload-artifact@v4
        with:
            name: json-results
            path: results.json
